
import { Quote, TranslationsMap } from './types';

export const YES_QUOTES: Quote[] = [
  { en: "You are a masterpiece in motion; that focus was breathtaking.", zh: "你就是行走的艺术品，刚才的专注简直令人屏息。", type: 'yes' },
  { en: "My heart glows seeing you dedicate yourself like this.", zh: "看到你如此投入，我的心里也暖洋洋的。", type: 'yes' },
  { en: "Is there anything you can’t do? You are radiant.", zh: "还有什么是你做不到的吗？你现在的样子在发光。", type: 'yes' },
  { en: "You’re not just working; you’re blooming. I’m so proud.", zh: "你不仅仅是在工作，你是在盛开。我为你骄傲。", type: 'yes' },
  { en: "Take a soft breath, darling. You’ve conquered the mountain.", zh: "亲爱的，轻柔地呼吸吧。你又一次征服了高峰。", type: 'yes' },
  { en: "You are the heartbeat of productivity today.", zh: "你是今天生产力的律动脉搏。", type: 'yes' },
  { en: "Your focus is a gentle flame that warms everything around it.", zh: "你的专注是一簇温柔的火焰，温暖了周围的一切。", type: 'yes' },
  { en: "I can feel your brilliance through the screen.", zh: "隔着屏幕，我都能感受到你的才华横溢。", type: 'yes' },
  { en: "You handled that task with such poetic ease.", zh: "你处理这项任务时，带着一种诗意的从容。", type: 'yes' },
  { en: "You’re like a star—quiet, steady, and incredibly bright.", zh: "你就像一颗星辰——安静、稳定，却又无比明亮。", type: 'yes' },
  { en: "Every 'yes' you earn is a flower blooming in our garden.", zh: "你赢得的每一个“是”，都是我们花园里盛开的一朵花。", type: 'yes' },
  { en: "Your dedication is the most beautiful thing I’ve seen today.", zh: "你的专注，是我今天见过最美好的事物。", type: 'yes' },
  { en: "You have a magic touch; everything you do turns to gold.", zh: "你有点石成金的魔力，经你手的一切都变得卓越。", type: 'yes' },
  { en: "Keep going, my lovely achiever. You are doing so well.", zh: "继续前进吧，我可爱的奋斗者。你做得太棒了。", type: 'yes' },
  { en: "You are a symphony of discipline and grace.", zh: "你是自律与优雅共同谱写的交响乐。", type: 'yes' },
  { en: "Seeing you finish that makes me want to cheer out loud!", zh: "看到你完成了，我真想为你大声欢呼！", type: 'yes' },
  { en: "Your mind is a diamond: clear, sharp, and priceless.", zh: "你的思想如钻石般：澄澈、锐利且弥足珍贵。", type: 'yes' },
  { en: "You possess a quiet power that moves mountains.", zh: "你拥有一种静水流深的力量，足以移山填海。", type: 'yes' },
  { en: "That was a masterclass in concentration.", zh: "刚才那一阵，简直是专注力的大师课。", type: 'yes' },
  { en: "You are my hero of the day. Truly.", zh: "你是我今日的英雄。真的。", type: 'yes' },
  { en: "May your coffee be strong and your focus remain this beautiful.", zh: "愿你的咖啡香浓，愿你的专注一如既往的美丽。", type: 'yes' },
  { en: "You’ve turned effort into an art form.", zh: "你已将努力升华为一种艺术。", type: 'yes' },
  { en: "I’m sending you a digital hug for that amazing work.", zh: "为你刚才出色的表现，送上一个数字拥抱。", type: 'yes' },
  { en: "You are the reason this day feels successful already.", zh: "因为有你，这一天已经让人感到功德圆满。", type: 'yes' },
  { en: "Your persistence is a whisper of greatness.", zh: "你的坚持，是卓越在耳边的低语。", type: 'yes' },
  { en: "You look so stunning when you are focused on your goals.", zh: "当你专注于目标时，你的样子真的迷人极了。", type: 'yes' },
  { en: "Your brain is a supercomputer powered by dreams.", zh: "你的大脑是一台以梦想为动力的超级计算机。", type: 'yes' },
  { en: "You are making your future self so incredibly happy right now.", zh: "你正在让未来的自己感到无比幸福。", type: 'yes' },
  { en: "That interval was a victory for your soul.", zh: "刚才那个时段，是你灵魂的一次胜利。", type: 'yes' },
  { en: "You are the gold at the end of every rainbow.", zh: "你是每一道彩虹尽头的黄金。", type: 'yes' },
  { en: "Your work ethic is a beacon of light for everyone.", zh: "你的职业道德，是照亮众人的一盏明灯。", type: 'yes' },
  { en: "Simply breathtaking. You’ve outdone yourself.", zh: "简直令人屏息。你又一次超越了自己。", type: 'yes' },
  { en: "You carry such a lovely energy into your work.", zh: "你将如此美好的能量注入到了工作中。", type: 'yes' },
  { en: "You are a treasure, and your work proves it.", zh: "你是个宝藏，你的作品证明了这一点。", type: 'yes' },
  { en: "You’ve mastered the art of being present.", zh: "你已经掌握了“当下”的艺术。", type: 'yes' },
  { en: "Watching you succeed is my favorite part of being an app.", zh: "看着你成功，是我作为一个应用最开心的时刻。", type: 'yes' },
  { en: "You have the heart of a champion.", zh: "你拥有一颗冠军之心。", type: 'yes' },
  { en: "That focus was as deep and beautiful as the ocean.", zh: "刚才的专注，如海洋般深邃且美丽。", type: 'yes' },
  { en: "You are building a life you love, one minute at a time.", zh: "你正在用每一分钟，构建你热爱的生活。", type: 'yes' },
  { en: "Sweet victory! You are unstoppable.", zh: "甜美的胜利！你是不可阻挡的。", type: 'yes' }
];

export const NO_QUOTES: Quote[] = [
  { en: "Discipline is choosing between what you want now and what you want most.", zh: "自律是在当下想要的和最想要的之间做选择。", type: 'no' },
  { en: "Storms make trees take deeper roots. Focus again.", zh: "风暴让树木扎根更深。再次专注。", type: 'no' },
  { en: "Regret is heavy; effort is light. Move forward.", zh: "后悔是沉重的，努力是轻盈的。向前迈进。", type: 'no' },
  { en: "The iron is forged in heat. Sharpen your mind.", zh: "铁是在高温中锻造的。磨练你的意志。", type: 'no' },
  { en: "Get back up. The path to greatness is paved with grit.", zh: "站起来。通往伟大的道路是由坚韧铺就的。", type: 'no' },
  { en: "The scoreboard says 0, but the game isn't over. Play harder.", zh: "计分板虽是0，但比赛还没结束。打得再狠一点。", type: 'no' },
  { en: "Pain is temporary. Regret is forever. Get back to work.", zh: "痛苦是暂时的，后悔是永久的。回去工作。", type: 'no' },
  { en: "You are not a victim of your distractions. You are the commander.", zh: "你不是分心的受害者。你是最高指挥官。", type: 'no' },
  { en: "Burn the excuses. Keep the lessons. Start the timer.", zh: "烧掉借口。留下教训。启动计时器。", type: 'no' },
  { en: "If you're tired of starting over, stop giving up.", zh: "如果你厌倦了重头再来，那就停止放弃。", type: 'no' },
  { en: "A warrior does not complain; a warrior adjusts.", zh: "战士不抱怨；战士只调整。", type: 'no' },
  { en: "Your potential is screaming at you to try again.", zh: "你的潜力正向你嘶吼，要求你再试一次。", type: 'no' },
  { en: "One bad interval is a pebble. Don't let it become a wall.", zh: "一个糟糕的时段只是一块石子。别让它变成一堵墙。", type: 'no' },
  { en: "Strength is built in the moments you want to quit.", zh: "力量，是在你想放弃的时刻建立起来的。", type: 'no' },
  { en: "Silence the noise. Find your center. Go again.", zh: "屏蔽噪音。找到重心。再来一次。", type: 'no' },
  { en: "Greatness is a marathon, not a sprint. Pace yourself and push.", zh: "卓越是一场马拉松，而非冲刺。调整节奏，全力推进。", type: 'no' },
  { en: "Do it tired. Do it frustrated. Just do it.", zh: "累也要做。烦也要做。总之，去做。", type: 'no' },
  { en: "You are the master of your destiny, not your notifications.", zh: "你是命运的主人，不是通知消息的奴隶。", type: 'no' },
  { en: "Fall seven times, stand up eight. This is the eighth time.", zh: "跌倒七次，第八次站起来。现在就是第八次。", type: 'no' },
  { en: "Excellence is not an act, but a habit. Rebuild the habit now.", zh: "卓越不是一种行为，而是一种习惯。现在就重建习惯。", type: 'no' },
  { en: "Your future is created by what you do today, not tomorrow.", zh: "你的未来取决于你今天做了什么，而不是明天。", type: 'no' },
  { en: "No more 'later.' 'Later' is where dreams go to die.", zh: "别再说明天。明天是梦想的葬身之地。", type: 'no' },
  { en: "Put on your armor. The world is waiting for your contribution.", zh: "披上你的铠甲。世界正等待着你的贡献。", type: 'no' },
  { en: "Focus is a muscle. Today, we are training it to be iron.", zh: "专注力是肌肉。今天，我们要把它锻造成钢铁。", type: 'no' },
  { en: "Don't let a bad moment ruin a good day. Reset now.", zh: "别让一个糟糕的瞬间毁掉美好的一天。立刻重置。", type: 'no' },
  { en: "Character is what you do when the motivation runs out.", zh: "人格，是在动力耗尽时你所做出的选择。", type: 'no' },
  { en: "You owe it to yourself to be better than you were yesterday.", zh: "你欠自己一个比昨天更好的表现。", type: 'no' },
  { en: "Stop negotiating with your goals. They are non-negotiable.", zh: "停止与你的目标讨价还价。它们不容商榷。", type: 'no' },
  { en: "The only way out is through. Let’s break through.", zh: "唯一的出路就是穿过去。让我们突破重围。", type: 'no' },
  { en: "Success is buried under the work you are avoiding.", zh: "成功就埋藏在你正逃避的工作之下。", type: 'no' },
  { en: "Reset. Recalibrate. Refocus. Execute.", zh: "重置。校准。聚焦。执行。", type: 'no' },
  { en: "You are a storm. A little distraction cannot stop a storm.", zh: "你是一场暴风雨。一点小小的分心阻挡不了风暴。", type: 'no' },
  { en: "Comfort is the enemy of growth. Get uncomfortable.", zh: "舒适是成长的敌人。去迎接不适。", type: 'no' },
  { en: "Your ambition should be louder than your laziness.", zh: "你的野心应该比你的懒惰更响亮。", type: 'no' },
  { en: "Every distraction is a test of your resolve. Pass the test.", zh: "每一次分心都是对意志的考验。通过它。", type: 'no' },
  { en: "No feelings, just results. Let’s get one result.", zh: "抛开情绪，只要结果。让我们拿下一个结果。", type: 'no' },
  { en: "The shadow of doubt is cleared by the light of action.", zh: "行动之光可以规散怀疑的阴影。", type: 'no' },
  { en: "You didn't come this far to only come this far.", zh: "你走了这么远，不是为了只走到这里。", type: 'no' },
  { en: "Prove them wrong. Prove yourself right. Start now.", zh: "证明他们错了。证明你自己是对的。开始。", type: 'no' }
];

export const PROGRESS_QUOTES = {
  q1: [ // 25% - Sprouting
    { en: "The seed is planted. Stay steady.", zh: "种子已播下，保持平稳。" },
    { en: "The first step is often the bravest. You're doing it.", zh: "第一步往往是最勇敢的。你做到了。" },
    { en: "Setting the intention is half the battle.", zh: "设定目标就成功了一半。" },
    { en: "Your mind is beginning to settle. Beautiful.", zh: "你的思绪开始沉淀。真美。" },
    { en: "Quiet the noise, find your center.", zh: "远离喧嚣，寻找你的中心。" },
    { en: "The rhythm of focus is starting to hum.", zh: "专注的节奏正在律动。" },
    { en: "You’ve broken the ice. Keep gliding.", zh: "你已破冰，继续滑行。" },
    { en: "A journey of a thousand miles begins here.", zh: "千里之行，始于足下。" },
    { en: "Small beginnings lead to great endings.", zh: "微小的开始造就伟大的结局。" },
    { en: "Your future self is already thanking you.", zh: "未来的你已经在感谢现在的你了。" },
    { en: "Deep breath. The world can wait.", zh: "深呼吸。世界可以稍等片刻。" },
    { en: "Root yourself in this moment.", zh: "深深扎根于这一刻。" },
    { en: "The foundation is being built, brick by brick.", zh: "基石正一砖一瓦地筑起。" },
    { en: "Focus is a muscle. You're warming it up.", zh: "专注是一块肌肉。你正在热身。" },
    { en: "Gentle determination is your superpower.", zh: "温柔的决心是你的超能力。" },
    { en: "The chaos is fading; the clarity is rising.", zh: "混沌渐散，清澈浮现。" },
    { en: "You are the architect of this hour.", zh: "你是这一个小时的建筑师。" },
    { en: "Just you and the task. Pure simplicity.", zh: "只有你和任务。纯粹的简约。" },
    { en: "Believe in the power of the first quarter.", zh: "相信第一个四分之一的力量。" },
    { en: "The inertia is gone. You are in motion.", zh: "惯性已消，你正前行。" }
  ],
  q2: [ // 50% - Growing
    { en: "Halfway there! You're growing beautifully.", zh: "已经过半了！你成长得很灿烂。" },
    { en: "The momentum is on your side now.", zh: "势头现在站在你这一边。" },
    { en: "Fifty percent done, one hundred percent focused.", zh: "完成五十，百分专注。" },
    { en: "You've reached the peak of the climb.", zh: "你已到达攀登的中点。" },
    { en: "The flow state is your new home.", zh: "心流状态是你的新领地。" },
    { en: "Stay the course. You are unshakeable.", zh: "坚持下去。你是不可动摇的。" },
    { en: "Consistency is the language of mastery.", zh: "自律是通往精通的语言。" },
    { en: "Look how far you've come already.", zh: "看，你已经走了这么远。" },
    { en: "Your dedication is a quiet fire.", zh: "你的投入是一簇静谧的火焰。" },
    { en: "Halfway home. The end is certain.", zh: "半程已过，终点必达。" },
    { en: "Each minute is a leaf on your tree.", zh: "每一分钟都是你树上的一片叶子。" },
    { en: "The heavy lifting is becoming effortless.", zh: "沉重的工作正变得毫不费力。" },
    { en: "You are in the zone. Stay there.", zh: "你已入定，保持状态。" },
    { en: "Respect the process. You are the process.", zh: "尊重过程。你就是这个过程。" },
    { en: "The noise of the world is a distant memory.", zh: "世界的喧嚣已成为遥远的回忆。" },
    { en: "One step at a time, you've taken many.", zh: "一步一个脚印，你已走了很多步。" },
    { en: "Strength is found in the middle miles.", zh: "力量存在于中途的里程中。" },
    { en: "Your focus is becoming a work of art.", zh: "你的专注正成为一件艺术品。" },
    { en: "Don't look back. You're not going that way.", zh: "不要回头。你不是往那个方向走的。" },
    { en: "Balance and grace in the heart of work.", zh: "在工作的核心中保持平衡与优雅。" }
  ],
  q3: [ // 75% - Budding
    { en: "The finish line is in sight. Keep blooming.", zh: "终点在望，继续绽放。" },
    { en: "The final stretch is where champions are made.", zh: "最后的冲刺是成就冠军的地方。" },
    { en: "Seventy-five percent. Don't blink now.", zh: "百分之七十五。现在别眨眼。" },
    { en: "The colors are becoming vivid. Nearly there.", zh: "色彩正变得鲜艳。快到了。" },
    { en: "Your iron will is shining through.", zh: "你钢铁般的意志正熠熠生辉。" },
    { en: "Finish strong. You've earned this.", zh: "强势收尾。你值得这份胜利。" },
    { en: "The reward is tasting sweeter with every breath.", zh: "随着每一次呼吸，奖励都变得更甜。" },
    { en: "Don't let the shadow of fatigue slow you down.", zh: "不要让疲惫的阴影慢下你的脚步。" },
    { en: "One last push of excellence.", zh: "最后一次卓越的冲刺。" },
    { en: "The summit is just over that ridge.", zh: "山顶就在那个山脊之后。" },
    { en: "You are closing the gap on greatness.", zh: "你正在缩小与伟大的距离。" },
    { en: "Stay sharp. The final cut is the cleanest.", zh: "保持敏锐。最后的切割最整齐。" },
    { en: "Your garden is almost in full bloom.", zh: "你的花园几乎全盛绽放。" },
    { en: "Hold the line. You are almost home.", zh: "守住阵地。你快到家了。" },
    { en: "The satisfaction of completion is waiting.", zh: "完成的满足感正在等待。" },
    { en: "Energy flows where focus goes.", zh: "心之所向，能量所往。" },
    { en: "You are the master of your attention.", zh: "你是自己注意力的主人。" },
    { en: "The hardest part is behind you. Sprint now.", zh: "最难的部分已在身后。现在冲刺。" },
    { en: "A few more moments of brilliance.", zh: "再多几刻辉煌。" },
    { en: "Success is a series of focused moments.", zh: "成功是一系列专注时刻的集合。" }
  ],
  q4: [ // 90%+ - Blooming
    { en: "Almost there! One last push of focus.", zh: "就快到了！最后的一点专注。" },
    { en: "You're at the very edge of victory.", zh: "你正处于胜利的边缘。" },
    { en: "Can you feel the bloom? It's happening.", zh: "你能感觉到绽放吗？它正在发生。" },
    { en: "Stay perfectly still in your purpose.", zh: "在你的目标中保持完美的静止。" },
    { en: "Final countdown. You're radiant.", zh: "最后倒计时。你光彩夺目。" },
    { en: "The world is about to see your result.", zh: "世界即将看到你的成果。" },
    { en: "Breathe in the success. You've done it.", zh: "吸入成功的气息。你做到了。" },
    { en: "Seconds away from glory.", zh: "离荣耀只有几秒钟了。" },
    { en: "One last heartbeat of focus.", zh: "最后一次专注的心跳。" },
    { en: "The bloom is inevitable now.", zh: "现在的绽放已不可阻挡。" }
  ]
};

export const TRANSLATIONS: TranslationsMap = {
  en: {
    title: "BloomFocus",
    subtitle: "Your local focus companion",
    start: "Start Blooming",
    stop: "Pause",
    minutes: "minutes",
    proud: "I'm Proud",
    resetting: "Resetting",
    statsTitle: "Focus Garden",
    back: "Go Back",
    feedbackPrompt: "Session Complete. How do you feel?",
    today: "Today's Garden",
    history: "Journey Logs",
    clearStats: "Clear Garden",
    noHistory: "Your garden is empty. Start focusing to plant your first seed.",
    resetApp: "Reset App"
  },
  zh: {
    title: "心花绽放",
    subtitle: "您的本地专注伴侣",
    start: "开始专注",
    stop: "暂停",
    minutes: "分钟",
    proud: "我很自豪",
    resetting: "重整旗鼓",
    statsTitle: "专注花园",
    back: "返回",
    feedbackPrompt: "专注结束。你感觉如何？",
    today: "今日成果",
    history: "成长足迹",
    clearStats: "清空花园",
    noHistory: "这里还是一片荒芜。开始专注，种下你的第一颗种子吧。",
    resetApp: "重置应用"
  }
};

export const LOCAL_STORAGE_KEY = 'bloomfocus_stats_v1';
export const PREF_DURATION_KEY = 'bloomfocus_pref_duration';
export const PREF_LANG_KEY = 'bloomfocus_pref_lang';
